name: Build OpenOCD - RPM

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "53 2 * * 1"

jobs:
  openocd-build:
    runs-on: ubuntu-20.04

    steps:
    - name: Build Version
      run: |
       export VERSION_TMP="$(date +'%Y%m%d.%H%M')"
       echo "::set-env name=VERSION::$VERSION_TMP"
       echo $VERSION

    - name: Setup build environment
      run: |
       sudo apt-get update
       sudo apt-get -y install \
       make libtool pkg-config autoconf automake \
       texinfo tree libusb-dev libusb-1.0 \
       libhidapi-dev libftdi-dev
       sudo apt-get -y install rpm

    - name: Prepare RPM build
      run: |
       mkdir -p ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/BUILD
       cp rpm-package/openocd.spec ~/rpmbuild/SPECS

    - name: Build RPM from spec file
      run: |
       cd ~/rpmbuild/SPECS
       rpmbuild -ba openocd.spec
       ls ~/rpmbuild/BUILD

    #- name: Debian package artifact
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: debian-package
    #    path: openocd-build.deb
